# NumPy Tutorial

In [147]:
#import Numpy and created own first array
import numpy as np

x = np.array([1,2,3,4,5])  # 1D array that contain integers

In [148]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [149]:
x.dtype #returns the data type of the element in that array. 
        #This d-type let us know that the element of x are stored in memory a signed 64-bit integer

dtype('int64')

In [150]:
x.shape #returns an integer indicating the length of the array, five (here) 

(5,)

In [151]:
y = np.array ([[1,2,3,4], [1,2,3,4], [1,2,3,4,], [1,2,3,4,], [1,2,3,4]])
print(y)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [152]:
y.shape #5 rows and 4 columns

(5, 4)

In [153]:
y.size # 20 elements

20

In [154]:
x = np.array(['Hello', 'Hola'])
print(x)

['Hello' 'Hola']


In [155]:
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [156]:
x = np.array([1,2,'hola'])
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

['1' '2' 'hola']
shape: (3,)
type: <class 'numpy.ndarray'>
dtype: <U21


In [157]:
x = np.array([1, 1.2, 3])
print(x, x.dtype)  #when the input is a float is called outcasting (lo hace para no perder precision en futuros calculos)

[1.  1.2 3. ] float64


In [158]:
x = np.array([1, 1.2, 3], dtype = np.int64) #to get integer even if it is a float
print(x, x.dtype) 

[1 1 3] int64


In [159]:
#to save array into a file named my_array.npy
x = np.array([1,2,4,5])
np.save('my_array', x) #dont forget the name of the variable where the array is

In [160]:
#we can load this document in a new variable using load function
y = np.load('my_array.npy')
print(x)

[1 2 4 5]


In [161]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [162]:
x = np.zeros((3,4))
print(x)
print('\ndtype:', x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

dtype: float64


In [163]:
x = np.zeros((3,4), dtype = np.int64)
print(x)
print('\ndtype:', x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

dtype: int64


In [164]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [165]:
x = np.full((4,3), 5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [166]:
print('dtype:', x.dtype)

dtype: int64


In [167]:
#identity matrix
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [168]:
#diagonal matrix
x = np.diag([10, 20, 30, 50])
print(x)
            

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [169]:
#arrays with specific numerical ranges, this have three argument: star, stop, step, if we not specifi one, the program
#will understand own argument like a stop
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [170]:
x = np.arange(4,10) #give us an array from 4 to 9
print(x)

[4 5 6 7 8 9]


In [171]:
x = np.arange(1, 14, 3) #star, stop, step, empieza en 1, termina en 14-1 y genera los números cada 3.
print(x)

[ 1  4  7 10 13]


In [172]:
#arrays with specific numerical ranges, this have three argument: star, stop and end.
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [173]:
x = np.linspace(0, 25, 10, endpoint = False)#si añadimos esto al final, elimina el último argumento
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [174]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [175]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [176]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [177]:
x = np.arange(20).reshape((10,2))
print(x)                      

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [178]:
x = np.linspace(0, 50, 10, endpoint = False).reshape((5,2))
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [179]:
#en machine learning necesitaremos crear matrices random, por ejemplo cuando inincializamos weight in a neural network.
x = np.random.random((3,3))
print(x)

[[0.1574861  0.72351916 0.93333466]
 [0.9114343  0.1280866  0.96762197]
 [0.38041017 0.64087004 0.50843488]]


In [180]:
x = np.random.randint(4,15,(3,2)) #lower bound(inclusive), uper bound(exclusive) and the shape.
print(x)

[[ 4 12]
 [11 12]
 [ 6 10]]


In [181]:
#created an array with a given shape that contains randoms numers picked from a normal distribution with a given mean
#and standard deviation
x = np.random.normal(0, 0.1, size=(1000,1000)) #created a 1000*1000 array froma normal distribution with 
                                               #mean = 0 , standart_deviation = 0.1, 
print(x)

[[ 0.07256491  0.04598688 -0.13618964 ... -0.01956285  0.01424626
  -0.2708211 ]
 [-0.01522261 -0.04600712 -0.02622168 ...  0.1569105   0.06529496
  -0.01627605]
 [ 0.05914572  0.04917201 -0.00955013 ...  0.00756537  0.20904819
   0.03811341]
 ...
 [ 0.02504786 -0.03579804  0.12933238 ...  0.13598087 -0.02819433
  -0.05027384]
 [-0.09796899  0.06757024  0.17765501 ... -0.16627005  0.067905
   0.05077646]
 [-0.01435157 -0.00142173  0.03318329 ...  0.08847982 -0.08056593
  -0.04518566]]


In [182]:
print('mean:', x.mean())
print('std:', x.std())
print('max:', x.max())
print('min:', x.min())
print('# positive:', (x > 0).sum())
print('# negative:', (x < 0).sum())

mean: -3.232437050727807e-05
std: 0.09997608885018872
max: 0.47139690617342506
min: -0.4594160011044528
# positive: 499799
# negative: 500201


# Accessing, Deleting, and Inserting Elements Into ndarrays

In [184]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [185]:
print('1st element:', x[0])  #positives for the begginenig
print('2st element:', x[1])
print('5st element:', x[4])

1st element: 1
2st element: 2
5st element: 5


In [186]:
print('1st element:', x[-5])   #negatives for the end
print('2st element:', x[-4])
print('5st element:', x[-1])

1st element: 1
2st element: 2
5st element: 5


In [187]:
#modifi element in an array
x[3] = 20  #el numero que esta en la cuarta posición es cambiado 
print(x)


[ 1  2  3 20  5]


In [188]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [189]:
print('Element at (0,0):', x[0,0])
print('Element at (0,1):', x[0,1])
print('Element at (2,2):', x[2,2])

Element at (0,0): 1
Element at (0,1): 2
Element at (2,2): 9


In [190]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [191]:
x = np.array([1,2,3,4,5])
print('hemos creado esta array:', x)
#delete elements using Nunmpy´s delete function
x = np.delete(x,[0,4])
print('\nle hemos quitado el numero que estaba situado en posición numero cero y cuatro:', x)

hemos creado esta array: [1 2 3 4 5]

le hemos quitado el numero que estaba situado en posición numero cero y cuatro: [2 3 4]


In [192]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [193]:
z = np.delete(y, 0, axis=0)
print('\n', z)


 [[4 5 6]
 [7 8 9]]


In [194]:
g = np.delete(y, [0,2], axis=1)
print('\n', g)


 [[2]
 [5]
 [8]]


In [195]:
#add values with the append function
x = np.array([1,2,3,4,5])
print('hemos creado esta array:', x)

hemos creado esta array: [1 2 3 4 5]


In [196]:
x = np.append(x,[6])
print('\nañadimos el número seis:', x)


añadimos el número seis: [1 2 3 4 5 6]


In [197]:
x = np.append(x,[7,8])
print('\nañadimos los números 7 y 9', x)


añadimos los números 7 y 9 [1 2 3 4 5 6 7 8]


In [198]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [199]:
w = np.append(y, [[10,11,12]], axis=0)
print('\n', w)
print('\nThe shape has changed:', w.shape)


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

The shape has changed: (4, 3)


In [200]:
z = np.append(y, [[10],[11],[12]], axis=1)
print('\n', z)
print('\nThe shape has changed:', z.shape)


 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]

The shape has changed: (3, 4)


In [201]:
#insert values with insert function wich take an array, index, element and axis

x = np.array([1,2,5,6,7])
print(x)


[1 2 5 6 7]


In [202]:
#We are going to insert values 3 and four between 2 and 5.

x = np.insert(x,2,[3,4])
print(x)

[1 2 3 4 5 6 7]


In [203]:
y = np.array([[1,2,3],[7,8,9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [204]:
w = np.insert(y,1,[4,5,6], axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [205]:
z = np.insert(y,1,5, axis=1)
print(z)

[[1 5 2 3]
 [7 5 8 9]]


In [206]:
#do an arrays with other array
x = np.array([1,2])
print(x)

[1 2]


In [207]:
y = np.array([[3,4], [5,6]])
print(y)

[[3 4]
 [5 6]]


In [208]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [209]:
w = np.hstack((y, x.reshape(2,1))) #we need to reshape X to match the shape of Y before stacking it horizontally.
print(w)

[[3 4 1]
 [5 6 2]]


# Slicing ndarrays

1. ndarray[start:end] #slicing from a starting index to an ending index
2. ndarray[start:] #slicing from the start of index to the end of the array by living a blanck
3. ndarray[:end] #slicing from the beginning of the array to an ending index, by living a blanck part before
In the first and thrid methods, the ending index is always excluded.
In the first and second methods, the start index is always included.

In [228]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [212]:
z = x[1:4, 2:5] #the first part is for the rows and the second part for the columns
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [213]:
z = x[1:, 2:] #we can omit the final part. If we do not mention it, it will simply go to the end automatically.
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [214]:
z = x[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [215]:
z = x[:, 2] #all the rows in column 2
print(z)

[ 3  8 13 18]


In [216]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [218]:
z = x[:, 3:4]
print(z)

[[ 4]
 [ 9]
 [14]
 [19]]


In [219]:
z = x[:, 4:5]
print(z)

[[ 5]
 [10]
 [15]
 [20]]


In [229]:
print(x) #let´s see the diferent between see choises and making editions

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [230]:
z = x[1:, 2:] 
print(z) #here we are chousen
print('\n', x) # if we print x the output will still being x

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [231]:
z[2,2] = 555 #here we are editing
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [232]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [233]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [235]:
z = np.copy(x[1:,2:])
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [236]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


*Lets create a rank one array that will serve as indices to select elements from x*

In [240]:
import numpy as np
indices = np.array([1,3])
print(indices)

[1 3]


In [241]:
y = x [indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [244]:
z = x[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [245]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [243]:
z = np.diag(x)
print(z)

[ 0  6 12 18]


In [246]:
z = np.diag(x, k=1)
print(z)

[ 1  7 13 19]


In [247]:
z = np.diag(x, k=-1) #por defecto k es 0 por lo que k=1 va por encima de 0 y k=-1 por debajo de cero
print(z)

[ 5 11 17]


In [251]:
#we can find the unique element in array by using numpy´s unique function
x = np.array([[1,2,3], [4,5,6], [1,2,3]])
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [252]:
print(np.unique(x))

[1 2 3 4 5 6]


# **Boolean Indexing, Set Operations, and Sorting**

In [2]:
import numpy as np

In [3]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
#get elements higher than 10
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [8]:
#get elements less than or equal to 7
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [12]:
#get elements greater than 7 and less than 17
print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


In [13]:
#using boolena indexing to assign elements that are between 10 and 17 to the value of -1
x[(x>10) & (x<17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [14]:
#find comun elements
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

#we can create arrays for the intersection, difference and union

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [15]:
#sorting an array using sort function to sort rank one and rank two array in diffent ways
#the sort funtion can be used as a method, but there is a difference on how the data is stored in the memory in yhis case

x = np.random.randint(1, 11, size=(10,))
print(x)

[ 4  3  7  1 10  8 10  9  6  8]


In [17]:
print(np.sort(x)) #we can sort using sort as a function
print(x)

[ 1  3  4  6  7  8  8  9 10 10]
[ 4  3  7  1 10  8 10  9  6  8]


In [18]:
print(np.sort(np.unique(x)))
print(x)

[ 1  3  4  6  7  8  9 10]
[ 4  3  7  1 10  8 10  9  6  8]


In [19]:
x.sort()
print(x)

[ 1  3  4  6  7  8  8  9 10 10]


In [20]:
x = np.random.randint(1, 11, size=(5,5))
print(x)

[[ 5  1  4  1  2]
 [ 2  3  3  6  4]
 [ 4  9  1  8  3]
 [ 2  5  4 10  1]
 [ 1  8  4  2  8]]


In [22]:
print(np.sort(x, axis=0))

[[ 1  1  1  1  1]
 [ 2  3  3  2  2]
 [ 2  5  4  6  3]
 [ 4  8  4  8  4]
 [ 5  9  4 10  8]]


In [23]:
print(np.sort(x, axis=1))  #columns

[[ 1  1  2  4  5]
 [ 2  3  3  4  6]
 [ 1  3  4  8  9]
 [ 1  2  4  5 10]
 [ 1  2  4  8  8]]


#### QUIZ:

In [30]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
import numpy as np
X = np.arange(1,26).reshape(5,5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print(x)
print('\n',y)

[[ 5  1  4  1  2]
 [ 2  3  3  6  4]
 [ 4  9  1  8  3]
 [ 2  5  4 10  1]
 [ 1  8  4  2  8]]

 [6 7 2 8 4]


# Arithmetic operations and Broadcasting:

In [31]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [36]:
print(x + y)
print(np.add(x,y)) 
print('\nWe see the same result')

[ 6  8 10 12]
[ 6  8 10 12]

We see the same result


In [37]:
#Lets also try element-wise substraction, multiplication and division
print(x - y)
print(np.subtract(x,y))
print(x * y)
print(np.multiply(x,y))
print(x / y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [38]:
#To do this we have to be sure that the arrays hava the same shape or be broadcastable!!!

In [39]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [40]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [42]:
#Lets do the same operation that before using ths symbol notation

In [47]:
print(x + y, 'sum') #sum
print(x - y, 'subt') #subt
print(x * y, 'multi') #multi
print(x / y, 'divi') #divi


[[ 6  8]
 [10 12]] sum
[[-4 -4]
 [-4 -4]] subt
[[ 5 12]
 [21 32]] multi
[[0.2        0.33333333]
 [0.42857143 0.5       ]] divi


In [49]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [51]:
#we can get the square root of each element like this
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [52]:
#and the exponential os each like this
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [53]:
#ans also each element to the power of two
print(np.power(x,2))

[ 1  4  9 16]


##### Statitical functions

In [54]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [55]:
#average of all
print('average of all:', x.mean())

average of all: 2.5


In [59]:
#average of individual rows and columns
print('average of columns:', x.mean(axis=0))
print('average of rows:', x.mean(axis=1))

average of columns: [2. 3.]
average of rows: [1.5 3.5]


In [60]:
#sum
print('sum of all:', x.sum())
print('sum of columns:', x.sum(axis=0))
print('sum of rows:', x.sum(axis=1))

sum of all: 10
sum of columns: [4 6]
sum of rows: [3 7]


In [61]:
#standart de deviation
x.std()

1.118033988749895

In [62]:
#median
np.median(x)

2.5

In [63]:
#maximun
x.max()

4

In [64]:
#minimun
x.min()

1

In [66]:
#add single numbers to al the elementes of a NumPy array without the use of complicated loops
print(x)

[[1 2]
 [3 4]]


In [67]:
#add 3 to each element
print(3 + x)

[[4 5]
 [6 7]]


In [72]:
#subtrac 3 to each
print(x - 3)

[[-2 -1]
 [ 0  1]]


In [73]:
#multiply each by 3
print(x * 3)

[[ 3  6]
 [ 9 12]]


In [74]:
#divide each by 3
print(x / 3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [76]:
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [78]:
x = np.arange(3)
print(x)

[0 1 2]


In [80]:
print(y + x) #add zero to the first colum, 1 to the second and 2 to the third

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [82]:
z = np.arange(3).reshape(3,1)
print(z)

[[0]
 [1]
 [2]]


In [83]:
print(z + y) #add zero to the firt arrow,  1 to the second and 2 to the third

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


#### QUIZ:

In [84]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

x =  np.ones((4,4)) * np.arange(1,5)
print(x)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
